### ISSUE TITLE
the battery [is charging] status is error

### ISSUE THREAD

**Issue by xiaodang** [gao-sun/eul#111]
env:
OS: macOS Big Sur 11.0.1 20B29 x86_64 

pic:
![image](https://user-images.githubusercontent.com/7018239/100065729-1eec9200-2e6f-11eb-9b20-9adafb405fcb.png)

**Comment by gao-sun** [comment]
since your battery level is 100% macOS will stop charging and use AC power as power source. 

![image](https://user-images.githubusercontent.com/14722250/100339851-5bf28900-3015-11eb-9b2e-6653b7134d51.png)
![image](https://user-images.githubusercontent.com/14722250/100339860-601ea680-3015-11eb-92b4-3714108157f2.png)

It seems Big Sur doesn't differentiate this on icon. :-)

**Comment by xiaodang** [comment]
get it, thank you.
