### ISSUE TITLE
Installed successfully via brew...click to open....NOTHING?!

### ISSUE THREAD

**Issue by oregonpillow** [gao-sun/eul#32]
Doesn't open after successful installation. No error messages. Am I missing something? On MacOS 10.15.6

**Comment by oregonpillow** [comment]
It starts eventually just takes a really long time.

**Comment by gao-sun** [comment]
it's unusual. would you mind to uncheck network top activities and relaunch the app to see if it goes better? a potential high CPU usage caused by `nettop` has been reported.

also, it'll be great to run with `--debug` option and see past a snippet of output here. say you have eul in `/Applications` folder, then open terminal and run `/Applications/eul.app/Contents/MacOS/eul --debug`
